language: julia
os:
  # - windows
  - linux
  # - osx
julia:
  - 1.5
  
notifications:
  email: true

script:
  - julia --project -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(coverage=true);
                        Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());
                        Pkg.add("Documenter"); include("docs/make.jl")'
