language: julia
os:
  # - windows
  - linux
julia:
  - 1.3.1
codecov: true

notifications:
  email: false

script:
  - julia --project -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(coverage=true)'
