language: julia
os:
  # - windows
  - linux
julia:
  - 1.3.1

codecov: true

notifications:
  email: false

script:
  - julia --project -e 'using Pkg; Pkg.build(verbose=true); Pkg.test("NeuroAnalysis",coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("NeuroAnalysis")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
