language: julia
os:
  # - windows
  - linux
julia:
  - 1.3.1

notifications:
  email: true

# script:
#   - julia --project -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(coverage=true)'
#
# after_success:
#   - julia --project -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "Test"
      script:
        - julia --project -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(coverage=true)'
      after_success:
        - julia --project -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

    - stage: "Documentation"
      julia: 1.3.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
